name: Tao Rust

on:
  push:
    branches: [tao]
  pull_request:
    branches: [tao]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            rust: stable
          - os: ubuntu-latest
            rust: stable
          - os: ubuntu-latest
            rust: '1.89.0'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo test
      - run: cargo clippy --all-targets -- -D warnings
